- app/components/Navbar.tsx
- app/components/WalletDetails.tsx
This pull request introduces functionality for tracking user interactions and events using Mixpanel in the `Navbar` and `WalletDetails` components. The most important changes include importing the Mixpanel library, identifying users, and tracking various events such as wallet connections and funding completions.
* [`app/components/Navbar.tsx`](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR13): Imported the Mixpanel library and added user identification and event tracking in the `onComplete` callback of the `useLogin` hook. This includes setting user properties such as id (wallet address), login method, last login date, signup date, email, and whether the user is new. [[1]](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR …
> feat: implement user ID tracking on wallet connection and funding events

- .github/CODEOWNERS
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?pvs=4) for how to create and submit a high-quality PR for this repo.
> This pull request includes a change to the `.github/CODEOWNERS` file to specify default code owners for the repository.
* [`.github/CODEOWNERS`](diffhunk://#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R1-R5): Added default owners `@chibie` and `@jeremy0x` for the entire repository.
> `.github/CODEOWNERS`
> fix: Create CODEOWNERS

- app/components/Navbar.tsx
- Added an invisible bridge element to maintain hover state between trigger and dropdown menu
- Grouped logo and arrow icon together for better interaction consistency
- Improved dropdown positioning to prevent layout shifts
- Added proper aria labels for better screen reader support
- Added a Home link on the navbar for easy navigation back home from the legal pages
- (additional) Change the "Sign In" text to sentence case
The previous implementation had issues where users would lose the dropdown when trying to move their cursor to it. This change makes the navigation more user-friendly by:
1. Creating a seamless hover area between trigger and menu
2. Making both logo and arrow function as dropdown triggers
3. Maintaining consistent layout during dropdown interactions
> fix(navbar): improve dropdown hover behavior and accessibility

- app/pages/TransactionForm.tsx
Also limited fiat (receive) amount to 2 decimal places to match standard currency format
- Fixed input field bug that prevented entering numbers longer than 4 digits
- Users can now enter any length of whole numbers (only limited by max value of 10,000)
- Previous implementation incorrectly limited the length of the whole number part
- Limited fiat (receive) amount to 2 decimal places to match standard currency format
- Kept crypto (send) amount at 4 decimal places
- Verified numbers like 12345 can now be entered (though invalid if >10000)
- Confirmed decimal place limits work correctly:
- Send amount: up to 4 decimal places (e.g. 1234.5678)
- Receive amount: up to 2 decimal places (e.g. 1234.56)
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of …
> fix: remove character limit on numeric input fields

- app/api/aggregator.ts
- app/page.tsx
- app/types.ts
This PR adds support for fetching rates from specific liquidity providers by adding a new URL parameter `LP`. This allows users to get quotes from their preferred providers and enables direct deep linking to specific provider rates.
Key changes:
- Added `providerId` optional parameter to rate fetching
- Modified rate API endpoint to support provider filtering
- Updated types to include provider ID in rate payloads
- Added URL parameter extraction and handling
- Added failed providers tracking to prevent repeated failed requests
- Improved error handling with automatic fallback to public queue
Example usage:
```
https://noblocks.xyz/?LP=sampleID             // Gets rates only from sampleID provider
https://noblocks.xyz/                         // Gets rates from all providers (default …
```
> feat: add provider-specific rate fetching via LP URL param

- app/page.tsx
This PR fixes the recent build error by wrapping the page’s `useSearchParams` call in a Suspense boundary to prevent client-side forced rendering and resolve the missing Suspense boundary build issue.
This pull request includes changes to the `app/page.tsx` file to enhance the component structure and improve the handling of search parameters. The most important changes include the addition of new imports, the refactoring of the `Home` component, and the introduction of a new `SearchParamsWrapper` component.
Component structure improvements:
* [`app/page.tsx`](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L3-R3): Added `Suspense` and `JSX` to the import statement to support asynchronous rendering and JSX elements.
* …
> fix: wrap useSearchParams in Suspense to resolve build error

- app/page.tsx
This pull request includes a change to the `app/page.tsx` file to improve the user experience by updating the fallback component in the `Suspense` wrapper.
* [`app/page.tsx`](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L322-R322): Replaced the fallback component in the `Suspense` wrapper from a simple `<div>Loading...</div>` to a more informative `<Preloader isLoading={true} />` component.
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?pvs=4) for how to create and submit a …
> fix: replace loading fallback with Preloader component in Suspense

- app/utils.ts
This pull request includes a change to the `kenyaMobileMoneyOptions` array in the `app/utils.ts` file. The change updates the code for the "SAFARICOM (MPESA)" institution from "MPESA" to "SAFAKEPC".
* [`app/utils.ts`](diffhunk://#diff-9ba22a4ee607f76b338e5793ffbb2eae933b1b432aba0fbcd3a3fd14c9efbb1bL316-R316): Updated the `code` for "SAFARICOM (MPESA)" from "MPESA" to "SAFAKEPC".
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?pvs=4) for how to create and submit a high-quality PR for this repo.
> fix: update Kenya mobile money code for SAFARICOM (MPESA) to correct value

- app/components/FlexibleDropdown.tsx
- app/components/KycModal.tsx
- app/components/MobileDropdown.tsx
- app/components/PDFReceipt.tsx
- app/components/TransferModal.tsx
- app/components/WalletDetails.tsx
- app/components/recipient/RecipientDetailsForm.tsx
- app/context/BalanceContext.tsx
- app/context/NetworksContext.tsx
- app/page.tsx
- app/pages/TransactionForm.tsx
- app/pages/TransactionPreview.tsx
- app/pages/TransactionStatus.tsx
This pull request includes changes to the `TransactionPreview` component in the `app/pages/TransactionPreview.tsx` file. The changes primarily involve the addition of a new dependency and the use of URL search parameters within the component.
Key changes:
* Added import for `useSearchParams` from `next/navigation` to handle URL search parameters.
* Introduced `searchParams` constant to retrieve search parameters within the `TransactionPreview` component.
* Updated `prepareCreateOrderParams` function to include `providerId` from search parameters if available.
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing …
> feat: include provider ID in recipient data

- package.json
- pnpm-lock.yaml
This pull request includes updates to the `next` package and its related dependencies across multiple files. The primary goal is to upgrade from version 15.1.6 to 15.2.0.
Changelog: <https://nextjs.org/blog/next-15-2>
Package updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L37-R37): Updated `next` from 15.1.6 to 15.2.0.
Dependency updates in `pnpm-lock.yaml`:
* Updated `next` version specification and resolution from 15.1.6 to 15.2.0 in the `importers` section.
* Updated multiple `@next` package versions from 15.1.6 to 15.2.0 in the `packages` section. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL591-R640) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee …
> chore(deps): update Next.js version from 15.1.6 to 15.2.0

- app/pages/TransactionForm.tsx
This pull request enhances the swap functionality by enabling form validation when the user clicks the "Max" button. This ensures that the form inputs are validated, improving the overall user experience.
- [] This change adds test coverage for new/changed/fixed functionality
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?pvs=4) for how to create and submit a high-quality PR for this repo.
> fix: enable form validation when setting max balance amount

- app/components/NetworkSelectionModal.tsx
- app/components/NetworksDropdown.tsx
- app/context/InjectedWalletContext.tsx
This pull request includes several changes to improve the handling of search parameters and the structure of the `InjectedWalletProvider` component. The most important changes include refactoring the use of `searchParams` to use `next/navigation`, and restructuring the `InjectedWalletProvider` to include a `Suspense` fallback.
Improvements to search parameter handling:
* [`app/components/NetworkSelectionModal.tsx`](diffhunk://#diff-003f8681a0a763f0ca123183e908e9519a7afed953763acc146200146eb04eabR13-L20): Replaced the usage of `URLSearchParams` with `useSearchParams` from `next/navigation` for better integration with Next.js.
* [`app/components/NetworksDropdown.tsx`](diffhunk://#diff-241e6c4fddddee25f9d81714380c6763a22f43ba9f80710835e9b61eb6524665R5): Similar to `NetworkSelectionModal`, …
> feat: improve URL handling with useSearchParams hook

- app/pages/TransactionForm.tsx
This pull request enhance swap functionality by converting balance to 4 decimal place when user click for 'Max' button
https://github.com/paycrest/noblocks/issues/83
- [] This change adds test coverage for new/changed/fixed functionality
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?pvs=4) for how to create and submit a high-quality PR for this repo.
> fix:  Swap button disabling issue for values with more than 4 decimal places

- app/pages/TransactionForm.tsx
This pull request includes change of `TransactoinForm.tsx` and it is related with issue #102. Implemented feature is like below.
1. When User select token and change the network.
2. If the selected token is not supported 
3. Set the selected token as the first token of supported tokens.
>
> [BUG] Incorrect token display when switching networks #102 
> Closes #102 
###Impacts
> Implemented one useEffect hook in `TransactionForm.tsx`
> If `selctedNetwork.chain.name` is changed run `initSelectedToken`
1. Go to the swap page on the Arbitrum network.
2. Select USDT as the token.
3. Switch the network to Base.
4. Observe that the displayed selected token is changed USDC(first token of Base).
- [x ] I have added documentation and tests for new/changed functionality in this PR
- [x ] All active …
> fix: update selected token when selected network is changed to another

- app/pages/TransactionForm.tsx
> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
This PR is to fix the unsupported token by the network provided in the URL the API fetches the rate of the unsupported tokens and no error message is provided
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, contracts etc.
- Replaced the static tokens in `setDefaultValueOnPageLoad` with dynamically fetched supported tokens based on the network
- Created a boolean `useRef` named `isFirstRender` to prevent multiple display of error
- Added an user friendly toast error with title and description
- Closes #101 
> Describe how this …
> fix unsupported token issue in url

- app/components/MobileDropdown.tsx
- app/components/SettingsDropdown.tsx
- app/hooks/useWalletDisconnect.ts
This pull request introduces the `useWalletDisconnect` hook, which facilitates the disconnection of a user's wallet from the application. The hook leverages the createWalletClient function to interact with the Ethereum provider, allowing for the revocation of wallet permissions
- Cloess #91 
By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).
> feat: Disconnect external wallets on sign-out

- app/components/MobileDropdown.tsx
- app/components/SettingsDropdown.tsx
This pull request introduces several changes to the `MobileDropdown` and `SettingsDropdown` components to support multi-factor authentication (MFA) functionality. The most important changes include importing necessary hooks and icons, adding a button to trigger the MFA enrollment modal, and ensuring consistent code formatting.
Enhancements for MFA support:
* [`app/components/MobileDropdown.tsx`](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109L6-R6): Added `useMfaEnrollment` hook and `Key01Icon` import to support MFA functionality. [[1]](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109L6-R6) [[2]](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109R19)
* …
> feat: add MFA management option to settings

- app/pages/TransactionForm.tsx
- app/pages/TransactionStatus.tsx
This PR updates the transaction status component to update the layout, text and component arrangement to match the updated design. Below is a comparison of the before and after look of the component.
| Before | After (Successful tx) | After (Failed tx) |
|--------|--------|--------|
| ![Screenshot 2025-03-27 at 23-53-58 Noblocks](https://github.com/user-attachments/assets/62485355-87a1-40d7-ad22-40f95c68f845) | ![Screenshot 2025-03-28 at 01-16-24 Noblocks](https://github.com/user-attachments/assets/8fc7a62b-2659-43af-9aed-f75d46a821d5) | ![Screenshot 2025-03-28 at 01-15-46 Noblocks](https://github.com/user-attachments/assets/ab7f6f89-a893-4a07-aa9e-4e79f730d39f) | 
By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Condu …
> style: update tx status layout

- app/components/TransactionHelperText.tsx
- app/components/index.ts
- app/pages/TransactionPreview.tsx
- app/pages/TransactionStatus.tsx
This pull request introduces a new `TransactionHelperText` component and integrates it into the transaction-related pages. The component displays helper text after a delay during long-running transactions to inform users about the status of their transaction. The most important changes include the creation of the `TransactionHelperText` component, its export, and its integration into the `TransactionPreview` and `TransactionStatus` pages.
New component creation:
* [`app/components/TransactionHelperText.tsx`](diffhunk://#diff-230558889123c2aa8e7e950758df961acdae1e732cf6694adf449fdcd2c288a3R1-R62): Created the `TransactionHelperText` component that displays helper text after a specified delay during long-running transactions.
Component export:
* …
> feat: display helper text for long running transactions

- app/components/MobileDropdown.tsx
- app/components/SettingsDropdown.tsx
This pull request introduces conditional rendering to both the `MobileDropdown` and `SettingsDropdown` components to ensure that certain buttons or elements are only displayed when `isInjectedWallet` is false. This improves the user interface by hiding irrelevant options for users with injected wallets.
* **`MobileDropdown` component (`app/components/MobileDropdown.tsx`)**:
- Wrapped the MFA enrollment button in a conditional block to render it only when `isInjectedWallet` is false. [[1]](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109R452) [[2]](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109R465)
* **`SettingsDropdown` component (`app/components/SettingsDropdown.tsx`)**:
- Added a conditional block to ensure a specific …
> fix: conditionally render MFA enrollment button for non-injected wallets

- app/page.tsx
Updated the rate fetching logic to convert `USDbC` to `USDC` before making the API call. This ensures that the correct token is used for fetching rates, improving compatibility with rate-fetching logic.
* **Token conversion for rate fetching**:
- Added logic to convert `USDbC` to `USDC` before passing the token to the `fetchRate` function, ensuring consistent handling of token identifiers. (`[app/page.tsxR171-R175](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0R171-R175)`)
> #115 
- On the beta version of noblocks:
- Switch to base network
- Select the `USDbC` token
- Select a currency
- Verify rate is properly fetched without errors
By submitting a PR, I agree to Paycrest's [Contributor Code of …
> fix: convert USDbC to USDC for accurate rate fetching

- app/hooks/useConfetti.ts
- app/pages/TransactionStatus.tsx
This PR improves the transaction status page animations and user experience by:
- Simplifies the confetti animation to a minimal top-to-bottom pour effect
- Prevents confetti from re-firing on component re-renders
- Fixes beneficiaries checkbox visibility:
- Only shows for successful transactions (validated/settled)
- Hides if recipient is already in beneficiaries list
- Stabilizes checkmark animation to prevent unnecessary re-renders
These changes enhance the user experience by:
- Making animations more subtle and professional
- Preventing redundant visual feedback
- Improving the clarity of the beneficiaries feature
- Reducing unnecessary re-renders and animations
- Verify confetti only fires once on successful transaction
- Confirm beneficiaries checkbox only shows for successful …
> refactor: improve transaction status animations and beneficiaries visibility

- app/page.tsx
This pull request includes a minor update to the `useForm` initialization in the `HomeImpl` function. The change explicitly specifies the generic type parameters for `useForm`, adding `any` and `undefined` for the second and third parameters, respectively.
* [`app/page.tsx`](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L60-R60): Updated the `useForm` call in the `HomeImpl` function to include explicit generic type parameters: `<FormData, any, undefined>`.
By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).
> fix: update useForm type definition for improved type safety

- app/components/MobileDropdown.tsx
This pull request adds new functionality to the `MobileDropdown` component, specifically introducing buttons for "Transfer" and "Fund" actions when certain conditions are met.
* Added a conditional block to render "Transfer" and "Fund" buttons when `isInjectedWallet` is false and `isLoading` is false. These buttons trigger the `setIsTransferModalOpen` and `setIsFundModalOpen` functions respectively. (`app/components/MobileDropdown.tsx`, [app/components/MobileDropdown.tsxR288-R306](diffhunk://#diff-da0424d36864efc6eae58426bbffee8a857e2f6e22d3ddf1e8fd122582581109R288-R306))
By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution …
> fix: restore transfer and fund buttons to mobile dropdown

- app/pages/TransactionForm.tsx
This PR fixes an issue where the "Get Started" button remains disabled for users who need to complete KYC verification, even after they've funded their wallet, entered an amount, and selected a currency.
The root cause was that form fields weren't being properly marked as "dirty" in React Hook Form when values were programmatically set using `setValue()`. By default, React Hook Form only marks fields as dirty when the user explicitly interacts with them, which meant the `isDirty` condition in `useSwapButton.ts` was not being satisfied when values were set programmatically.
This PR adds the `shouldDirty: true` option to all instances of `setValue()` throughout the TransactionForm component, ensuring that fields are properly marked as dirty when values are programmatically changed, …
> fix: enable "Get Started" button for KYC after form values are set

- app/mocks.ts
- app/utils.ts
This pull request adds support for two new currencies, the Ugandan Shilling (UGX) and Tanzanian Shilling (TZS), by updating mock data and mapping logic in the codebase.
* [`app/mocks.ts`](diffhunk://#diff-5cef9b68abafa52ec52595fa36fc23b188891a59f1e0df39f92559ebec5ac0eaR17-R24): Added entries for UGX and TZS to the `acceptedCurrencies` list, including their names and labels.
* [`app/utils.ts`](diffhunk://#diff-9ba22a4ee607f76b338e5793ffbb2eae933b1b432aba0fbcd3a3fd14c9efbb1bR666-R667): Updated the `currencyToCountryCode` function to include mappings for UGX (Uganda) and TZS (Tanzania).
- Closes #136
> feat: add support for Ugandan Shilling (UGX) and Tanzanian Shilling

- app/pages/TransactionPreview.tsx
This PR optimizes the block range used for polling `OrderCreated` events in the transaction preview component. Currently, the system uses a fixed 25-block range for all networks, which may not be optimal for different blockchain networks with varying block times and confirmation patterns.
**Changes:**
- **Arbitrum One**: Uses 25 blocks (maintains current behavior)
- **Other networks**: Uses 10 blocks (reduced for better performance)
This optimization improves the efficiency of event polling by using network-specific block ranges, which can help with:
- Faster event detection on networks with shorter block times
- Reduced RPC calls for networks that don't need the full 25-block range
- Better reliability across different blockchain networks
**No breaking changes** - this is a performance …
> fix: optimize block range for order event polling

- app/components/transaction/PausedNetworkNotice.tsx
- app/pages/TransactionForm.tsx
This PR removes the BSC (BNB Smart Chain) paused network notification and all associated blocking functionality. BSC is now back online after the migration, so users should be able to perform transactions on the BSC network without restrictions.
**Changes made:**
- Removed `PausedNetworkNotice` component entirely
- Removed `isPausedNetwork` logic from `TransactionForm.tsx` 
- Removed BSC network blocking that prevented transactions
- Cleaned up component imports and exports
The BSC network is now fully operational and users can perform swaps without the previous migration-related restrictions.
This change addresses the user request to remove BSC blocking since BSC is back up and operational.
**Manual testing steps:**
1. Navigate to the transaction form
2. Select BSC network
3. Verify no …
> feat: remove BSC paused network notification and blocking

- app/pages/TransactionForm.tsx
This PR improves error handling for rate fetching in the transaction form.  
If fetching the rate fails (e.g., network error, no provider, etc.):
- The UI now displays **'No available quote'** instead of the rate (e.g., "1 USDT ~ 1,525 NGN").
- The actual error message is shown in a toast notification for user feedback.
- The rate display is only shown if there is no error and a valid rate is available.
No business logic or min/max calculation was changed in this commit—only error handling and user feedback for rate fetching.
N/A
To test:
1. Simulate a rate fetch failure (e.g., disconnect network, use unsupported pair, or force an error in the API).
2. The UI should show **'No available quote'** in place of the rate.
3. A toast notification should appear with the actual error message.
4. …
> fix(rates): show 'No available quote' and toast on rate fetch error
