paycrest/noblocks

app/components/Navbar.tsx
app/components/PDFReceipt.tsx
app/pages/TransactionForm.tsx
app/privacy-policy/page.tsx
app/terms/page.tsx

This pull request includes updates to the navigation and page components, primarily focusing on the addition of navigation hooks and UI enhancements.
* [`app/components/Navbar.tsx`](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR5): Added `usePathname` from `next/navigation` to conditionally render the "Home" link based on the current path. [[1]](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR5) [[2]](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR19) [[3]](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faR101-R109)
* [`app/privacy-policy/page.tsx`](diffhunk://#diff-8ebb0c839f2b580ce443adc7717c07dbc32b275e713b0dc4000ce7faaf13bdb4R4-R9): Added a "Go back" …

fix: resolve bugs across the app

---

app/components/FlexibleDropdown.tsx
app/components/Footer.tsx
app/components/Navbar.tsx
app/components/Preloader.tsx
app/components/SettingsDropdown.tsx
app/components/WalletDetails.tsx
app/components/recipient/RecipientDetailsForm.tsx
app/hooks/analytics/useMixpanel.ts
app/page.tsx
app/pages/TransactionPreview.tsx
app/pages/TransactionStatus.tsx
tailwind.config.ts

This pull request includes various updates and improvements to multiple components in the codebase. The changes focus on enhancing the user interface, improving functionality, and cleaning up the code. Below are the most important changes grouped by theme:
* [`app/components/FlexibleDropdown.tsx`](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL92-R92): Adjusted dropdown menu's z-index and padding, increased image size, and modified text size for better visual consistency. [[1]](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL92-R92) [[2]](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL110-R118) [[3]](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL132-R1 …

fix: bug fixes and improvements

---

app/components/ThemeSwitch.tsx
app/components/recipient/RecipientDetailsForm.tsx
app/components/recipient/RecipientListItem.tsx
app/hooks.ts
app/page.tsx
app/pages/TransactionForm.tsx
next.config.mjs
package.json
pnpm-lock.yaml

This pull request includes several updates and improvements across multiple files, focusing on improving amount input field validation, recipient details management across component, and next.js upgrade to version 15.
* [`app/components/recipient/RecipientDetailsForm.tsx`](diffhunk://#diff-f55d357dcca48e1e9293ccf2650c905b319905f7a6f077bb88259f45ca905dd3R77-R79): Added state management for returning from preview and simplified recipient details management. [[1]](diffhunk://#diff-f55d357dcca48e1e9293ccf2650c905b319905f7a6f077bb88259f45ca905dd3R77-R79) [[2]](diffhunk://#diff-f55d357dcca48e1e9293ccf2650c905b319905f7a6f077bb88259f45ca905dd3R223-R257)
* [`app/page.tsx`](diffhunk://#diff-6efdf509a785a0658b2e31a8c33d298de14321d9672179370e99cc76241c1eb0L55-R68): Introduced default form values and …

fix: upgrade next to v15, improve recipient details management and input validation

---

README.md

> This pull request includes a small change to the `README.md` file. The change updates the image URLs to point to the correct `main` branch and adds a note to check the Privy documentation for more information.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L34-R36): Updated image URLs to point to the `main` branch and added a note to check the Privy documentation for more information.
> `README.md`
By submitting a PR to this repository, you agree to the terms within the [Paycrest Code of Conduct](https://www.notion.so/paycrest/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c?pvs=4). Please see the [contributing guidelines](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a?p …

fix: tweak privy setup

---

app/components/Disclaimer.tsx
app/components/Navbar.tsx
app/components/index.ts
app/page.tsx
app/utils.ts

This pull request introduces a new `Disclaimer` component and updates the `Navbar` component to differentiate between the beta and production environments. It also includes utility updates and integrates the `Disclaimer` into the main page.
* [`app/components/Disclaimer.tsx`](diffhunk://#diff-3c5c27ccc4b1be82befa7002f05442ae648d7f76ecf5222e8291b200b30b9051R1-R128): Added a new `Disclaimer` component that displays a modal for users to accept a disclaimer notice. The modal appears if the user has not previously accepted the disclaimer and the domain is not the main production domain.
* [`app/components/Navbar.tsx`](diffhunk://#diff-9bdebf4ad9f663cb4edcaad6eb7093480dea11a66830384e2d11c399002fd8faL7-R17): Modified the `Navbar` component to display different logos based on whether the domain …

feat: add Disclaimer component and update Navbar for production domain check

---

app/components/Disclaimer.tsx
app/components/Footer.tsx
app/components/KycModal.tsx
app/components/MobileDropdown.tsx
app/components/Navbar.tsx
app/components/NetworksDropdown.tsx
app/components/PrivacyPolicy.tsx
app/components/SettingsDropdown.tsx
app/components/TermsOfService.tsx
app/components/WalletDetails.tsx
app/context/NetworksContext.tsx
app/page.tsx
app/pages/TransactionForm.tsx
app/pages/TransactionPreview.tsx
app/pages/TransactionStatus.tsx
app/types.ts

This pull request includes significant changes to the event tracking system, primarily removing events no longer needed and adding new ones. Additionally, there are updates to the handling of user actions and error messages.
Event tracking removal:
* [`app/components/Footer.tsx`](diffhunk://#diff-65edf535b119e7cb1b653d5546abcf5d2f3d35d580ce5d54c63574ba22533862L63-R62): Removed calls to `trackEvent` for social link clicks and the "Powered by Paycrest Protocol" link. [[1]](diffhunk://#diff-65edf535b119e7cb1b653d5546abcf5d2f3d35d580ce5d54c63574ba22533862L63-R62) [[2]](diffhunk://#diff-65edf535b119e7cb1b653d5546abcf5d2f3d35d580ce5d54c63574ba22533862L103-L107)
* [`app/components/KycModal.tsx`](diffhunk://#diff-bc8ca4e316207db37dc1bfa0aac3e1278766c0066781d204e2fceabd0f4db433L121-R126): …

fix: update events tracked for analytics

---

app/components/ImageAssets.tsx
app/components/KycModal.tsx
app/components/TransferModal.tsx
app/components/WalletDetails.tsx
app/hooks/useSwapButton.ts
app/pages/TransactionForm.tsx
package.json
pnpm-lock.yaml

This pull request includes significant updates to the `KycModal` component, modifications to the `CheckIcon` component, and minor changes to other components and hooks. The primary focus is on improving the user experience for KYC verification and ensuring proper handling of modal states.
* Removed `Dialog`, `DialogBackdrop`, and `DialogPanel` imports and related code, replacing them with simpler state management for opening and closing the modal. [[1]](diffhunk://#diff-bc8ca4e316207db37dc1bfa0aac3e1278766c0066781d204e2fceabd0f4db433L2-L15) [[2]](diffhunk://#diff-bc8ca4e316207db37dc1bfa0aac3e1278766c0066781d204e2fceabd0f4db433L435-R466)
* Simplified the terms acceptance process by consolidating terms into a single state and updating the UI to reflect these changes. …

Clean up KYC process

---

app/components/FundWalletModal.tsx
app/components/ImageAssets.tsx
app/components/MobileDropdown.tsx
app/components/Navbar.tsx
app/components/WalletDetails.tsx
app/components/index.ts
app/components/recipient/RecipientListItem.tsx
app/components/recipient/SavedBeneficiariesModal.tsx
app/components/recipient/SearchInput.tsx
app/hooks/useFundWalletHandler.ts
app/pages/TransactionForm.tsx
app/pages/TransactionPreview.tsx
app/pages/TransactionStatus.tsx

This pull request introduces significant changes to the `FundWalletModal` component and its integration within the application. The key changes include the creation of the `FundWalletModal` component, the removal of the `TrashIcon`, and the refactoring of the `MobileDropdown` and `WalletDetails` components to use the new modal for funding operations.
* [`app/components/FundWalletModal.tsx`](diffhunk://#diff-a8b874499f6eebf707c6c546e9f43e7fdfea55b0b376277c8a66b961cc0a338bR1-R220): Created a new `FundWalletModal` component to handle the wallet funding process. This includes form handling, token selection, and network display.
* [`app/components/ImageAssets.tsx`](diffhunk://#diff-6fb393fe44148f93e5b6645180177821eb9fd3eee9b75ba009378079035fa1d1L602-L630): Removed the `TrashIcon` component.
* …

feat: implement new fund wallet flow

---

app/components/FlexibleDropdown.tsx
app/components/NetworksDropdown.tsx
app/components/SettingsDropdown.tsx
app/layout.tsx
app/pages/TransactionForm.tsx

This pull request includes several updates to the styling of dropdown components and layout adjustments within the application. The changes mainly focus on improving the spacing, padding, and transition effects of various elements.
Styling updates:
* [`app/components/FlexibleDropdown.tsx`](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL53-R53): Updated the `DropdownContent` component to add padding and adjust the transition effects for better user experience. [[1]](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL53-R53) [[2]](diffhunk://#diff-44fc13e28e30c71087ce0b7235d568c1438d755e1352535a67d8940a56b00e0dL63-R63)
* [`app/components/NetworksDropdown.tsx`](diffhunk://#diff-241e6c4fddddee25f9d81714380c6763a22f43ba9f80710835 …

fix: update dropdown hover state and adjust adjust main container height

---

app/pages/TransactionForm.tsx

This pull request includes significant updates to the `TransactionForm` component in the `app/pages/TransactionForm.tsx` file. The changes focus on improving the handling and display of numerical input values, particularly for formatting numbers with commas and handling decimal points.
Key changes include:
* Enhanced the `import` statement to include `classNames` from `../utils`.
* Added state variables `formattedSentAmount` and `formattedReceivedAmount` to manage formatted input values.
* Introduced `formatNumberWithCommasForDisplay` to format numbers with commas while preserving decimal places.
* Added `removeCommas` function to strip commas from numbers for calculation and validation.
* Implemented `useEffect` hooks to update formatted display values when the actual values change.
* …

feat: add comma separators to amount input fields

---

app/utils.ts

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, contracts etc.
>
> If the UI is being changed, please provide screenshots.
> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed e.g closes #407
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.
> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this project has unit …

add USDT on base

---

app/components/FundWalletModal.tsx
app/components/MobileDropdown.tsx
app/components/TransferModal.tsx
app/components/WalletDetails.tsx
app/hooks/useFundWalletHandler.ts
app/pages/TransactionForm.tsx
app/utils.ts

This pull request introduces several enhancements and bug fixes across multiple components in the application. The key changes include adding a completion callback to the wallet funding process, improving the user experience during funding and transfer operations, and handling the completion state more effectively.
* [`app/components/FundWalletModal.tsx`](diffhunk://#diff-a8b874499f6eebf707c6c546e9f43e7fdfea55b0b376277c8a66b961cc0a338bL22-R26): Added an optional `onComplete` callback to the `onFund` method to handle the completion state. Introduced a `fundingInProgress` state to manage UI updates during the funding process. Updated the modal close behavior to reset the form and handle the funding state appropriately. [[1]](diffhunk://#diff-a8b874499f6eebf707c6c546e9f43e7fdfea55b0b376277c8a …

feat: improve fund wallet and transfer funds modal state management & completion flows

---

app/client.ts
app/context/BalanceContext.tsx
app/lib/privy-config.ts
app/pages/TransactionPreview.tsx

This pull request includes several changes across multiple files to improve the handling of Binance Smart Chain (BSC) network configurations, update transport URLs, and add comments for better code clarity. The most important changes include the removal of a redundant client creation, updating BSC transport URLs, and adding comments to explain wallet handling logic.
* [`app/client.ts`](diffhunk://#diff-1bc90032b41b385695e5b4c712e8ff79067ddf7026d085bdab7e82fe185d4ec5L1-L7): Removed the creation of a redundant `publicClient` for the base chain.
* [`app/lib/privy-config.ts`](diffhunk://#diff-a75f13515c5b7d1eebf8b7129cf0651e0d2fdda045afbd528be3a9ee26d288d6L2-R10): Added `bscOverride` to include a new RPC URL for BSC and updated the `supportedChains` configuration to use `bscOverride`. …

fix: update BSC RPC URL endpoint

---

app/components/TransferModal.tsx

Refactor token address and decimals retrieval to handle cases where token data is not found. Added error handling to display a clear message when token data is unavailable, improving user feedback during transaction failures.
Improvements to error handling:
* Added a check for `tokenAddress` and `tokenDecimals` and set an error message if token data is not found. This ensures that the user is informed when the specified token is not available.
* Enhanced the error logging in the catch block to provide more detailed information about the transfer failure, including the error object, short message, full error, token, and available tokens.
Code readability improvements:
* Refactored the code to use a single search for token data, reducing redundancy and improving readability.
This PR fixes …

fix: improve token data retrieval in TransferModal

---

app/pages/TransactionForm.tsx

This pull request includes several changes to the `TransactionForm` component in `app/pages/TransactionForm.tsx`. The changes focus on fixing typographical errors, improving code readability, and updating the logic for setting minimum and maximum transaction amounts.
* Introduced `minAmountSentValue` to dynamically set the minimum amount based on the exchange rate for `cNGN`. [[1]](diffhunk://#diff-9a85969750b7b7def7a17bbfc4d355c1ed1a37f96ac5405752a3fb3e8cfb24e2R284) [[2]](diffhunk://#diff-9a85969750b7b7def7a17bbfc4d355c1ed1a37f96ac5405752a3fb3e8cfb24e2R300-R313)
* Corrected the typo `isFirsRender` to `isFirstRender` in multiple places. [[1]](diffhunk://#diff-9a85969750b7b7def7a17bbfc4d355c1ed1a37f96ac5405752a3fb3e8cfb24e2L66-R66) …

fix: update minimum cNGN amount logic

---

app/components/WalletDetails.tsx
app/context/BalanceContext.tsx
app/context/NetworksContext.tsx

This pull request includes minor updates to improve code quality and consistency across the codebase. The changes involve fixing a typo in a string, adding a missing TypeScript type annotation, and suppressing an ESLint warning.
* [`app/components/WalletDetails.tsx`](diffhunk://#diff-2d2f6cafa992c1e8fb7bed5df555ec1d5c988552500481ba87c0e01990fccdb0L363-R363): Fixed a typo in the string by replacing the apostrophe with the HTML entity `&apos;` to ensure proper rendering in JSX.
* [`app/context/BalanceContext.tsx`](diffhunk://#diff-1bd75f62570fd9cb0ec4fd47278dab3754005849afc5e02db6d34dc86abf9201R142): Added an ESLint directive (`// eslint-disable-next-line react-hooks/exhaustive-deps`) to suppress a warning for the `useEffect` dependency array.
* …

fix: resolve build errors

---

app/page.tsx

Revert "fix: convert USDbC to USDC for accurate rate fetching"

---

app/components/TransferModal.tsx

> auto-generated
This pull request refactors the `TransferModal` component in `app/components/TransferModal.tsx` to improve code readability and maintainability. The changes include restructuring the conditional rendering logic and fixing minor formatting inconsistencies.
* Simplified the `return` statement by restructuring the conditional rendering logic to ensure the `AnimatedModal` component always wraps the content, regardless of the `isTransferSuccess` state. [[1]](diffhunk://#diff-3e0a616ac7a48e9a348a198088b2764045b344a226b96ef32d181a2d04b23989L223-L226) [[2]](diffhunk://#diff-3e0a616ac7a48e9a348a198088b2764045b344a226b96ef32d181a2d04b23989R356)
* Adjusted the indentation in the `validate` object to improve readability, specifically for the `length` validation rule.
> Closes #129 …

refactor: streamline TransferModal component structure

---

app/components/AnimatedComponents.tsx
app/components/FAQs.tsx
app/components/FlexibleDropdown.tsx
app/components/FormDropdown.tsx
app/components/FundWalletModal.tsx
app/components/HomePage.tsx
app/components/MobileDropdown.tsx
app/components/NetworksDropdown.tsx
app/components/Preloader.tsx
app/components/TransferModal.tsx
app/components/WalkthroughVideo.tsx
app/components/wallet-mobile-modal/FundView.tsx
app/components/wallet-mobile-modal/HistoryView.tsx
app/components/wallet-mobile-modal/SettingsView.tsx
app/components/wallet-mobile-modal/TransferView.tsx
app/components/wallet-mobile-modal/WalletView.tsx
app/components/wallet-mobile-modal/index.ts
app/globals.css
app/pages/TransactionForm.tsx

This PR introduces significant enhancements to the mobile wallet experience alongside critical bug fixes for dropdown components. The changes include a complete modularization of the mobile wallet interface, animated error handling, and improved UI consistency across the platform.
**Major Features & Improvements:**
1. **Mobile Wallet Modularization** (`MobileDropdown.tsx` + new `wallet-mobile-modal/` components):
- **Complete architectural refactor** of MobileDropdown into modular view components
- Created dedicated components: `WalletView`, `TransferView`, `FundView`, `HistoryView`, and `SettingsView`
- Transformed MobileDropdown from a monolithic component (1076 lines reduced) into a clean orchestrator
- **Enhanced mobile functionality**: Users can now send tokens and fund wallets …

feat: enhance mobile wallet experience and fix dropdown stacking issues

---

README.md

This PR merges the main branch into stable to ensure both branches are synchronized and to trigger the release workflow.
**Changes:**
- Sync commit to ensure main and stable are aligned
- Trigger release workflow for proper version management
- Follows the release workflow pattern established in previous releases
**Environment:** Next.js 14, React 18, TypeScript, Tailwind CSS
By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4a) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).

Sync: Merge main into stable

---

app/components/FundWalletForm.tsx
app/components/TransferForm.tsx
app/components/blog/post/detail-client.tsx
app/components/blog/post/table-of-contents.tsx

- Fixed React Hook useEffect missing dependencies warning in table-of-contents.tsx
- Fixed React Hook useMemo missing dependency warning in detail-client.tsx  
- Fixed TypeScript error in MobileDropdown.tsx by replacing 'any' with proper union types
- Added MobileView type for setCurrentView props in TransferForm and FundWalletForm
- Ensured all hooks follow Rules of Hooks and have correct dependencies
✅ Build passes successfully with no errors or warnings

fix: resolve build errors and hook deps
